name: Testing

on:
  pull_request:
     branches:
       - main

jobs:
  test-build:
    runs-on: ubuntu-latest
    environment: testing
    
    steps: 
     - uses: actions/checkout@v3
     
     - name: Run a one-line script
       run: |
           echo "Running one-line script"
           sleep 1m
           echo "Finish running scripts"
           
  prod-build:
     runs-on: ubuntu-latest
     environment: production
     needs: test-build
     
     steps:
      - uses: actions/checkout@v3
      
      - name: Run a multi-line script
        run: |
          echo "running multi-line script"
          sleep 1m
          echo "finish running multi-line script"
